In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls "/content/drive/MyDrive"

 24BCE8197_Week01_CreatingTables.pdf  'maths diff equ.pdf'
 Ai_Ml_projecs			       p1.jpeg
 Classroom			       Screenshot_20250522-173429.jpg
'Colab Notebooks'		       Screenshot_20250530-110749.jpg
'Eng lab'			      'Screenshot 2026-04-21 204710.png'
 Links2.gsheet			       TASK.gsheet
'Links .gsheet'			      'Untitled spreadsheet.gsheet'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    "/content/drive/MyDrive/Ai-Ml-projects/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projects/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Ai-Ml-projects/Student_placement_predictor/dataset/college_student_placement_dataset.csv'

In [ ]:
!ls "/content/drive/MyDrive/Ai-Ml-projects"

ls: cannot access '/content/drive/MyDrive/Ai-Ml-projects': No such file or directory

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projects/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Ai_Ml_projects/Student_placement_predictor/dataset/college_student_placement_dataset.csv'

In [ ]:
!ls "/content/drive/MyDrive"

 24BCE8197_Week01_CreatingTables.pdf  'maths diff equ.pdf'
 Ai_Ml_projecs			       p1.jpeg
 Classroom			       Screenshot_20250522-173429.jpg
'Colab Notebooks'		       Screenshot_20250530-110749.jpg
'Eng lab'			      'Screenshot 2026-04-21 204710.png'
 Links2.gsheet			       TASK.gsheet
'Links .gsheet'			      'Untitled spreadsheet.gsheet'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv
/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/Copy of college_student_placement_dataset.csv

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

shows all the rows and columns

In [ ]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [ ]:
df.shape()

TypeError: 'tuple' object is not callable

In [ ]:
shows number of rows and columns

In [ ]:
df.shape

(10000, 10)

shows all the columns

In [ ]:
df.columns

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='object')

In [ ]:
shows the datatypes of the attributes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

shows the statistical data

In [ ]:
df.describe()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

selecting inputs(features) and outputs

In [ ]:
X = df[
    [
        "IQ",
        "CGPA",
        "Academic_Performance",
        "Internship_Experience",
        "Extra_Curricular_Score",
        "Communication_Skills",
        "Projects_Completed",
    ]
]

y = df["Placement"]

In [ ]:
x.head()
y.head()

NameError: name 'x' is not defined

In [ ]:
x.head()

NameError: name 'x' is not defined

showing the inputs

In [ ]:
X.head()

,IQ,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
0,107,6.28,8,No,8,8,4
1,97,5.37,8,No,7,8,0
2,109,5.83,9,No,3,1,1
3,122,5.75,6,Yes,1,6,1
4,96,7.69,7,No,8,10,2

showing shape of inputs

In [ ]:
X.shape

(10000, 7)

In [ ]:
Y.head()
Y.shape

NameError: name 'Y' is not defined

In [ ]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: Placement, dtype: object

In [ ]:
y.shape

(10000,)

In [ ]:
X.info()

print("\nTarget values:")
print(y.unique())

print("\nTarget data type:")
print(y.dtype)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IQ                      10000 non-null  int64
 1   CGPA                    10000 non-null  float64
 2   Academic_Performance    10000 non-null  int64
 3   Internship_Experience   10000 non-null  object
 4   Extra_Curricular_Score  10000 non-null  int64
 5   Communication_Skills    10000 non-null  int64
 6   Projects_Completed      10000 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 547.0+ KB

Target values:
['No' 'Yes']

Target data type:
object

showing the values of exp

In [ ]:
df["Internship_Experience"].value_counts()

Internship_Experience
No     6036
Yes    3964
Name: count, dtype: int64

In [ ]:

df["Internship_Experience"].value_counts()

df["Placement"].value_counts()

Placement
No     8341
Yes    1659
Name: count, dtype: int64

since it is in obj type we have to convert into 0 and 1

In [ ]:
df["Internship_Experience"] = df["Internship_Experience"].map({
    "No": 0,
    "Yes": 1
})

In [ ]:
df["Placement"] = df["Placement"].map({
    "No": 0,
    "Yes": 1
})

In [ ]:
df["Internship_Experience"].value_counts()

Internship_Experience
0    6036
1    3964
Name: count, dtype: int64

In [ ]:
df["Placement"].value_counts()

Placement
0    8341
1    1659
Name: count, dtype: int64

In [ ]:
refeaturing after labelling into 0 and 1s

In [ ]:
X = df[
    [
        "IQ",
        "CGPA",
        "Academic_Performance",
        "Internship_Experience",
        "Extra_Curricular_Score",
        "Communication_Skills",
        "Projects_Completed"
    ]
]

y = df["Placement"]

trainin and testing the model nex sep

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (8000, 7)
X_test : (2000, 7)
y_train: (8000,)
y_test : (2000,)

In [ ]:
model.fit(X_train, y_train)

NameError: name 'model' is not defined

importing the model and training it

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

finding accuracy score

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.895

since data is biased the accuracy alone not sufficient so we checking confusion matrix

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[1591   83]
 [ 127  199]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1674
           1       0.71      0.61      0.65       326

    accuracy                           0.90      2000
   macro avg       0.82      0.78      0.80      2000
weighted avg       0.89      0.90      0.89      2000

checking with decision tree

In [1]:
from sklearn.tree import DecisionTreeClassifier

In [2]:
dt_model = DecisionTreeClassifier(random_state=42)

In [3]:
dt_model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [4]:
df = pd.read_csv(...)

NameError: name 'pd' is not defined

In [7]:
import panda as pd

ModuleNotFoundError: No module named 'panda'

In [6]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

NameError: name 'pd' is not defined

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
!ls "/content/drive/MyDrive"

 24BCE8197_Week01_CreatingTables.pdf  'maths diff equ.pdf'
 Ai_Ml_projecs			       p1.jpeg
 Classroom			       Screenshot_20250522-173429.jpg
'Colab Notebooks'		       Screenshot_20250530-110749.jpg
'Eng lab'			      'Screenshot 2026-04-21 204710.png'
 Links2.gsheet			       TASK.gsheet
'Links .gsheet'			      'Untitled spreadsheet.gsheet'

In [1]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv'

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!ls "/content/drive/MyDrive"

 24BCE8197_Week01_CreatingTables.pdf  'maths diff equ.pdf'
 Ai_Ml_projecs			       p1.jpeg
 Classroom			       Screenshot_20250522-173429.jpg
'Colab Notebooks'		       Screenshot_20250530-110749.jpg
'Eng lab'			      'Screenshot 2026-04-21 204710.png'
 Links2.gsheet			       TASK.gsheet
'Links .gsheet'			      'Untitled spreadsheet.gsheet'

In [4]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/dataset/college_student_placement_dataset.csv"
)

In [5]:
df["Internship_Experience"] = df["Internship_Experience"].map({
    "No": 0,
    "Yes": 1
})

df["Placement"] = df["Placement"].map({
    "No": 0,
    "Yes": 1
})

In [6]:
X = df[
    [
        "IQ",
        "CGPA",
        "Academic_Performance",
        "Internship_Experience",
        "Extra_Curricular_Score",
        "Communication_Skills",
        "Projects_Completed"
    ]
]

y = df["Placement"]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

dt_pred = dt_model.predict(X_test)

print("="*50)
print("Decision Tree Results")
print("="*50)

print("Accuracy:", accuracy_score(y_test, dt_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

==================================================
Decision Tree Results
==================================================
Accuracy: 1.0

Confusion Matrix:
[[1674    0]
 [   0  326]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [10]:
print(X.columns)

Index(['IQ', 'CGPA', 'Academic_Performance', 'Internship_Experience',
       'Extra_Curricular_Score', 'Communication_Skills', 'Projects_Completed'],
      dtype='object')

In [11]:
print(X_train.shape)
print(X_test.shape)

(8000, 7)
(2000, 7)

In [12]:
dt_pred = ?

SyntaxError: invalid syntax (3823872710.py, line 1)

In [13]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [14]:
duplicates = df.groupby([
    "IQ",
    "CGPA",
    "Academic_Performance",
    "Internship_Experience",
    "Extra_Curricular_Score",
    "Communication_Skills",
    "Projects_Completed"
])["Placement"].nunique()

print((duplicates > 1).sum())

0

In [15]:
print("Tree Depth:", dt_model.get_depth())
print("Number of Leaves:", dt_model.get_n_leaves())

Tree Depth: 4
Number of Leaves: 10

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [18]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [19]:
rf_pred = rf_model.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("="*50)
print("Random Forest Results")
print("="*50)

print("Accuracy:", accuracy_score(y_test, rf_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

==================================================
Random Forest Results
==================================================
Accuracy: 1.0

Confusion Matrix:
[[1674    0]
 [   0  326]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [21]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance)

                  Feature  Importance
1                    CGPA    0.281637
5    Communication_Skills    0.270468
0                      IQ    0.242337
6      Projects_Completed    0.177361
4  Extra_Curricular_Score    0.012819
2    Academic_Performance    0.012044
3   Internship_Experience    0.003335

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [25]:
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [26]:
knn_pred = knn_model.predict(X_test_scaled)

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("="*50)
print("KNN Results")
print("="*50)

print("Accuracy:", accuracy_score(y_test, knn_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, knn_pred))

print("\nClassification Report")
print(classification_report(y_test, knn_pred))

==================================================
KNN Results
==================================================
Accuracy: 0.9415

Confusion Matrix
[[1641   33]
 [  84  242]]

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      1674
           1       0.88      0.74      0.81       326

    accuracy                           0.94      2000
   macro avg       0.92      0.86      0.89      2000
weighted avg       0.94      0.94      0.94      2000

In [28]:
import joblib

In [29]:
joblib.dump(
    rf_model,
    "/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/models/random_forest_model.pkl"
)

['/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/models/random_forest_model.pkl']

In [30]:
import os

os.listdir("/content/drive/MyDrive/Ai_Ml_projecs/Student_placement_predictor/models")

['random_forest_model.pkl']